import type { NextPage } from 'next';
import Head from 'next/head';
import VehicleCard from '../components/cards/VehicleCard/VehicleCard';
import { mockVehicleCardProps } from '../components/cards/VehicleCard/VehicleCard.mocks';
import SiteFooter from '../components/footer/footerMain';
import SiteHeader from '../components/header/headerMain';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SiteHeader></SiteHeader>

      <main className={styles.main}>
        <div className={styles.grid}>
          <VehicleCard {...mockVehicleCardProps.base} />
          <VehicleCard {...mockVehicleCardProps.base} />
          <VehicleCard {...mockVehicleCardProps.base} />
          <VehicleCard {...mockVehicleCardProps.base} />
        </div>
      </main>

      <SiteFooter></SiteFooter>
    </div>
  );
};

export default Home;
